### ISSUE TITLE
Problems with sharing links that contain a #

### ISSUE THREAD

**Issue by emptyturtle** [mwllgr/ic-yourls-android#4]
Hey, as I said, the app works well overall. 
But I noticed that if I share urls that have a # in them, everything is deleted after and with the #. If I share the link directly via YOURLS then it works so I assume it's a bug from the app. 

Thank you
best regards

**Comment by mwllgr** [comment]
Hi Lukas,

will look into this as soon as possible. Thank you for the report!

Best

**Comment by emptyturtle** [comment]
> Hi Lukas,
> 
> will look into this as soon as possible. Thank you for the report!
> 
> Best
 
👍 Thank you

**Comment by mwllgr** [comment]
Also, as a quick workaround, even though this is only suitable for manual shortening:

Shortening URLs with a # works if you replace the `#` with `%23` (the URL-encoded form of the # character)

**Comment by emptyturtle** [comment]
> Also, as a quick workaround, even though this is only suitable for manual shortening:
> 
> Shortening URLs with a # works if you replace the `#` with `%23` (the URL-encoded form of the # character)

Ah, works perfectly.
Of course, it would be more practical if this would happen automatically, but take your time with it. Thanks again for this app 👍

**Comment by mwllgr** [comment]
Hello,

I just uploaded version 1.2.6 (build 11) to the Play Store. This version includes a fix for the problem you described for both manual shortening and shortening via the share function. It'll take a few hours until it's available for download.

Please confirm the fix of the bug after updating so I can close the issue.
Thanks again for the report!

**Comment by emptyturtle** [comment]
> Please confirm the fix of the bug after updating so I can close the issue. Thanks again for the report!

Confirmed, works perfectly. Thank you for the fast fix.
